initial_shipping_homepage:
    path:     /
    defaults: { _controller: InitialShippingBundle:Default:index }

readexcelcontroller:
     path:    /readmy
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:index" }
fileadd:
     path:    /add
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:up" }
upload:
     path:    /upload
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:upload" }
newupload:
     path:    /newupload
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:newupload" }
showfile:
     path:    /showfile
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:showfile" }
downloadexcel:
       path:    /{filename}/downloadexcel
       defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:downloadexcel" }
highchart:
      path:     /highchart
      defaults: { _controller: "InitialShippingBundle:Highchart:chart"}
areachart:
      path:     /areachart
      defaults: { _controller: "InitialShippingBundle:Highchart:areachart"}
piechart:
            path:     /piechart
            defaults: { _controller: "InitialShippingBundle:Highchart:piechart"}
showchart:
      path:     /showchart
      defaults: { _controller: "InitialShippingBundle:Highchart:showchart"}
addchart:
      path:     /addchart
      defaults: { _controller: "InitialShippingBundle:Highchart:addchart"}
addcomment:
      path:     /addcomment
      defaults: { _controller: "InitialShippingBundle:Highchart:addcomment"}
showcomment:
      path:     /showcomment/{page}
      defaults: { _controller: "InitialShippingBundle:Highchart:showcomment"}
downloadchart:
       path:    /{filename}/downloadchart
       defaults: { _controller: "InitialShippingBundle:Highchart:downloadchart" }

downloadPdf:
      path:     /downloadPdf
      defaults: { _controller: "InitialShippingBundle:Highchart:downloadPdf"}
hello:
    path:     /hello
    defaults: { _controller: "InitialShippingBundle:Highchart:sendbackend" }
user_index:
    path: register/show
    defaults: { _controller: "InitialShippingBundle:UserActivitiy:index1" }
mycontroller:
        path: /{id}/mycontroller
        defaults: { _controller: "InitialShippingBundle:UserActivitiy:edit1" }
delete_user:
        path: /{id}/userdelete
        defaults: { _controller: "InitialShippingBundle:UserActivitiy:delete"}
company_edit:
        path: /useredit
        defaults: { _controller: "InitialShippingBundle:UserActivitiy:update"}
pdf:
   path: /pdf
   defaults: { _controller:"InitialShippingBundle:Highchart:createPdf"}
