initial_shipping_homepage:
    path:     /
    defaults: { _controller: InitialShippingBundle:Default:index }

readexcelcontroller:
     path:    /readmy
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:index" }
fileadd:
     path:    /add
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:up" }
upload:
     path:    /upload
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:upload" }
highchart:
      path:     /highchart
      defaults: { _controller: "InitialShippingBundle:Highchart:chart"}
showchart:
      path:     /showchart
      defaults: { _controller: "InitialShippingBundle:Highchart:showchart"}
addchart:
      path:     /addchart
      defaults: { _controller: "InitialShippingBundle:Highchart:addchart"}

downloadPdf:
      path:     /downloadPdf
      defaults: { _controller: "InitialShippingBundle:Highchart:downloadPdf"}


hello:
    path:     /hello
    defaults: { _controller: "InitialShippingBundle:Highchart:sendbackend" }
