initial_shipping_homepage:
    path:     /
    defaults: { _controller: InitialShippingBundle:Default:index }

readexcelcontroller:
     path:    /readmy
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:index" }
scorecard_import:
     path:    /add
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:up" }
upload:
     path:    /upload
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:upload" }
newupload:
     path:    /newupload
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:newupload" }
showfile:
     path:    /showfile
     defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:showfile" }
downloadexcel:
       path:    /{filename}/downloadexcel
       defaults: { _controller: "InitialShippingBundle:ReadExcelSheet:downloadexcel" }
highchart:
      path:     /highchart
      defaults: { _controller: "InitialShippingBundle:Highchart:chart"}
areachart:
      path:     /areachart
      defaults: { _controller: "InitialShippingBundle:Highchart:areachart"}
piechart:
            path:     /piechart
            defaults: { _controller: "InitialShippingBundle:Highchart:piechart"}
showchart:
      path:     /showchart
      defaults: { _controller: "InitialShippingBundle:Highchart:showchart"}
addchart:
      path:     /addchart
      defaults: { _controller: "InitialShippingBundle:Highchart:addchart"}
addcomment:
      path:     /addcomment
      defaults: { _controller: "InitialShippingBundle:Highchart:addcomment"}
showcomment:
      path:     /showcomment/{page}
      defaults: { _controller: "InitialShippingBundle:Highchart:showcomment"}
downloadchart:
       path:    /{filename}/downloadchart
       defaults: { _controller: "InitialShippingBundle:Highchart:downloadchart" }
runtimecomment:
      path:     /runtimecomment
      defaults: { _controller: "InitialShippingBundle:Highchart:runtimecomment"}
addcommentforshipreports:
      path:     /addcommentforshipreports
      defaults: { _controller: "InitialShippingBundle:Highchart:addcommentforshipreports"}
downloadPdf:
      path:     /downloadPdf
      defaults: { _controller: "InitialShippingBundle:Highchart:downloadPdf"}
hello:
    path:     /hello
    defaults: { _controller: "InitialShippingBundle:Highchart:sendbackend" }
user_index:
    path: register/show
    defaults: { _controller: "InitialShippingBundle:UserActivitiy:index1" }
mycontroller:
        path: /{id}/mycontroller
        defaults: { _controller: "InitialShippingBundle:UserActivitiy:edit1" }
delete_user:
        path: /{id}/userdelete
        defaults: { _controller: "InitialShippingBundle:UserActivitiy:delete"}
company_edit:
        path: /useredit
        defaults: { _controller: "InitialShippingBundle:UserActivitiy:update"}
runtimecommentforkpi:
            path:     /runtimecommentforkpi
            defaults: { _controller: "InitialShippingBundle:Highchart:runtimecommentforkpi"}
pdf:
   path: /pdf
   defaults: { _controller:"InitialShippingBundle:Highchart:createPdf"}

mail:
   path: /register/check_email
   defaults: { _controller: "InitialShippingBundle:CompanyUsers:emailName"}


mobile:
   path: /register/check_mobile
   defaults: { _controller: "InitialShippingBundle:CompanyUsers:mobileNumber"}

profile:
   path: /register/user_edit
   defaults: { _controller: "InitialShippingBundle:CompanyUsers:userShow"}

user:
   path: /register/sample_edit
   defaults: { _controller: "InitialShippingBundle:CompanyUsers:sample_edit"}

fos_user_registration_profile:
               path: /register/profile_change
               defaults: { _controller: "InitialShippingBundle:CompanyUsers:editall"}

document_read:
               path: /document
               defaults: { _controller: "InitialShippingBundle:CompanyUsers:Document"}
back_up:
         path: /backup
         defaults: { _controller: "InitialShippingBundle:CompanyUsers:Backup"}

import_db:
         path: /db_export
         defaults: { _controller: "InitialShippingBundle:CompanyUsers:dbBackup"}

view_file:
           path: /archived_report_view
           defaults: { _controller: "InitialShippingBundle:CompanyUsers:archivedReportShow"}

download_backup:
           path: /download_backup/{id}
           defaults: { _controller: "InitialShippingBundle:CompanyUsers:Download"}













