initial_shipping_ship_scorecard_report:
    resource: "@InitialShippingBundle/Controller/ScorecardReportController.php"
    type:     annotation

initial_shipping_ship_status_details:
    resource: "@InitialShippingBundle/Controller/ShipStatusDetailsController.php"
    type:     annotation

initial_shipping_ranking_rules:
    resource: "@InitialShippingBundle/Controller/RankingRulesController.php"
    type:     annotation

initial_shipping_ranking_element_rules:
    resource: "@InitialShippingBundle/Controller/RankingElementRulesController.php"
    type:     annotation

initial_shipping_ranking_kpi_rules:
    resource: "@InitialShippingBundle/Controller/RankingKpiRulesController.php"
    type:     annotation

initial_shipping_ranking_element_details:
    resource: "@InitialShippingBundle/Controller/RankingElementDetailsController.php"
    type:     annotation

initial_shipping_ranking_kpi_details:
    resource: "@InitialShippingBundle/Controller/RankingKpiDetailsController.php"
    type:     annotation

initial_shipping_ship_types:
    resource: "@InitialShippingBundle/Controller/ShipTypesController.php"
    type:     annotation

initial_shipping_apps_countries:
    resource: "@InitialShippingBundle/Controller/AppsCountriesController.php"
    type:     annotation

initial_shipping_kpi_rules:
    resource: "@InitialShippingBundle/Controller/KpiRulesController.php"
    type:     annotation
initial_shipping_mailing:
    resource: "@InitialShippingBundle/Controller/MailingController.php"
    type:     annotation

initial_shipping_dashborad:
    resource: "@InitialShippingBundle/Controller/DashboradController.php"
    type:     annotation
initial_shipping_chart:
    resource: "@InitialShippingBundle/Controller/ChartController.php"
    type:     annotation

initial_shipping_reading_kpi_values:
    resource: "@InitialShippingBundle/Controller/ReadingKpiValuesController.php"
    type:     annotation

initial_shipping_calculation_rules:
    resource: "@InitialShippingBundle/Controller/CalculationRulesController.php"
    type:     annotation

initial_shipping_rules:
    resource: "@InitialShippingBundle/Controller/RulesController.php"
    type:     annotation

initial_shipping_sub_element_details:
    resource: "@InitialShippingBundle/Controller/SubElementDetailsController.php"
    type:     annotation

initial_shipping_company_users:
    resource: "@InitialShippingBundle/Controller/CompanyUsersController.php"
    type:     annotation

initial_shipping_user_role:
    resource: "@InitialShippingBundle/Controller/UserRoleController.php"
    type:     annotation


initial_shipping_element_details:
    resource: "@InitialShippingBundle/Controller/ElementDetailsController.php"
    type:     annotation

initial_shipping_kpi_details:
    resource: "@InitialShippingBundle/Controller/KpiDetailsController.php"
    type:     annotation

initial_shipping_ship_details:
    resource: "@InitialShippingBundle/Controller/ShipDetailsController.php"
    type:     annotation

initial_shipping_company_details:
    resource: "@InitialShippingBundle/Controller/CompanyDetailsController.php"
    type:     annotation
initial_shipping_dataverfication_scorecard:
    resource: "@InitialShippingBundle/Controller/DataVerficationController.php"
    type:     annotation

initial_shipping:
    resource: "@InitialShippingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"




