<?php

namespace Initial\ShippingBundle\Repository;

/**
 * ArchivedReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivedReportRepository extends \Doctrine\ORM\EntityRepository
{
}
