<?php

namespace Initial\ShippingBundle\Repository;

/**
 * BackupreportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackupreportRepository extends \Doctrine\ORM\EntityRepository
{
}
