<?php

namespace Initial\ShippingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyDetailsRepository extends EntityRepository
{
}
