<?php

namespace Initial\ShippingBundle\Repository;

/**
 * ElementComparisonRulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementComparisonRulesRepository extends \Doctrine\ORM\EntityRepository
{
}
