<?php

namespace Initial\ShippingBundle\Repository;

/**
 * ElementSymbolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementSymbolsRepository extends \Doctrine\ORM\EntityRepository
{
}
