<?php

namespace Initial\ShippingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Excel_file_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Excel_file_detailsRepository extends EntityRepository
{
}
