<?php

namespace Initial\ShippingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KpiDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KpiDetailsRepository extends EntityRepository
{
}
