<?php

namespace Initial\ShippingBundle\Repository;

/**
 * KpiRulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KpiRulesRepository extends \Doctrine\ORM\EntityRepository
{
}