<?php

namespace Initial\ShippingBundle\Repository;

/**
 * RankingFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingFolderRepository extends \Doctrine\ORM\EntityRepository
{
}
