<?php

namespace Initial\ShippingBundle\Repository;

/**
 * RankingElementComparisonRulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingElementComparisonRulesRepository extends \Doctrine\ORM\EntityRepository
{
}
