<?php

namespace Initial\ShippingBundle\Repository;

/**
 * ScorecardDataImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScorecardDataImportRepository extends \Doctrine\ORM\EntityRepository
{
}
