<?php

namespace Initial\ShippingBundle\Repository;

/**
 * ScorecardFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScorecardFolderRepository extends \Doctrine\ORM\EntityRepository
{
}
