<?php

namespace Initial\ShippingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SendCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendCommandRepository extends EntityRepository
{
    public function countActiveRecords($category_id = null)
    {
        $qb = $this->createQueryBuilder('j')
            ->select('count(j.id)');


        if($category_id)
        {
            $qb->andWhere('j.clientemail = :category_id')
                ->setParameter('category_id', $category_id);
        }

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }
}
